server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organization?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zhujian.mtex.entity

configuration:
    map-underscore-to-camel-case: true
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true              #开启优化，<1页返回第一页
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false           #pageSize=0 返回所有
  params: count=countSql

#MQ连接配置
project:
  mq:
    host: 192.168.1.110
    port: 1414
    queue-manager: QM_APPLE         #队列管理器
    channel: SERVERCONN            #服务器连接通道
    username: fmy                  #用户名
    password: 123456               #密码
    receive-timeout: 2000          #连接超时